import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/sections/navbar/Navbar";
import Footer from "@/sections/footer/Footer";
// import Navbar from "@/sections/Navbar";

// const Switzer = localFont({
//   src: "https://fonts.cdnfonts.com/css/switzer",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Landingvault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-Switzer antialiased`}
      >

        <Navbar />
        <div className="mt-20">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
